# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

clientId: Optional[str]
"""
the [Client ID](https://docs.nobl9.com/sloctl-user-guide/#configuration) of your Nobl9 account required to connect to
Nobl9.
"""

clientSecret: Optional[str]
"""
the [Client Secret](https://docs.nobl9.com/sloctl-user-guide/#configuration) of your Nobl9 account required to connect
to Nobl9.
"""

ingestUrl: Optional[str]
"""
Nobl9 API URL.
"""

oktaAuthServer: Optional[str]
"""
Authorization service configuration.
"""

oktaOrgUrl: Optional[str]
"""
Authorization service URL.
"""

organization: Optional[str]
"""
Nobl9 [Organization ID](https://docs.nobl9.com/API_Documentation/api-endpoints-for-slo-annotations/#common-headers) that
contains resources managed by the Nobl9 Terraform provider.
"""

project: Optional[str]
"""
Nobl9 project used when importing resources.
"""

