# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .agent import *
from .alert_method_discord import *
from .alert_method_email import *
from .alert_method_jira import *
from .alert_method_msteams import *
from .alert_method_opsgenie import *
from .alert_method_pagerduty import *
from .alert_method_servicenow import *
from .alert_method_slack import *
from .alert_method_webhook import *
from .alert_policy import *
from .direct_appdynamics import *
from .direct_azure_monitor import *
from .direct_bigquery import *
from .direct_cloudwatch import *
from .direct_datadog import *
from .direct_dynatrace import *
from .direct_gcm import *
from .direct_honeycomb import *
from .direct_influxdb import *
from .direct_instana import *
from .direct_lightstep import *
from .direct_newrelic import *
from .direct_pingdom import *
from .direct_redshift import *
from .direct_splunk import *
from .direct_splunk_observability import *
from .direct_sumologic import *
from .direct_thousandeyes import *
from .get_aws_iam_role_external_id import *
from .project import *
from .provider import *
from .role_binding import *
from .service import *
from .slo import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import piclemx_pulumi_nobl9.config as __config
    config = __config
else:
    config = _utilities.lazy_import('piclemx_pulumi_nobl9.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "nobl9",
  "mod": "index/agent",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/agent:Agent": "Agent"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/alertMethodDiscord",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/alertMethodDiscord:AlertMethodDiscord": "AlertMethodDiscord"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/alertMethodEmail",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/alertMethodEmail:AlertMethodEmail": "AlertMethodEmail"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/alertMethodJira",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/alertMethodJira:AlertMethodJira": "AlertMethodJira"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/alertMethodMsteams",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/alertMethodMsteams:AlertMethodMsteams": "AlertMethodMsteams"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/alertMethodOpsgenie",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/alertMethodOpsgenie:AlertMethodOpsgenie": "AlertMethodOpsgenie"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/alertMethodPagerduty",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/alertMethodPagerduty:AlertMethodPagerduty": "AlertMethodPagerduty"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/alertMethodServicenow",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/alertMethodServicenow:AlertMethodServicenow": "AlertMethodServicenow"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/alertMethodSlack",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/alertMethodSlack:AlertMethodSlack": "AlertMethodSlack"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/alertMethodWebhook",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/alertMethodWebhook:AlertMethodWebhook": "AlertMethodWebhook"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/alertPolicy",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/alertPolicy:AlertPolicy": "AlertPolicy"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directAppdynamics",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directAppdynamics:DirectAppdynamics": "DirectAppdynamics"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directAzureMonitor",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directAzureMonitor:DirectAzureMonitor": "DirectAzureMonitor"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directBigquery",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directBigquery:DirectBigquery": "DirectBigquery"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directCloudwatch",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directCloudwatch:DirectCloudwatch": "DirectCloudwatch"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directDatadog",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directDatadog:DirectDatadog": "DirectDatadog"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directDynatrace",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directDynatrace:DirectDynatrace": "DirectDynatrace"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directGcm",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directGcm:DirectGcm": "DirectGcm"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directHoneycomb",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directHoneycomb:DirectHoneycomb": "DirectHoneycomb"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directInfluxdb",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directInfluxdb:DirectInfluxdb": "DirectInfluxdb"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directInstana",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directInstana:DirectInstana": "DirectInstana"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directLightstep",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directLightstep:DirectLightstep": "DirectLightstep"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directNewrelic",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directNewrelic:DirectNewrelic": "DirectNewrelic"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directPingdom",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directPingdom:DirectPingdom": "DirectPingdom"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directRedshift",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directRedshift:DirectRedshift": "DirectRedshift"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directSplunk",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directSplunk:DirectSplunk": "DirectSplunk"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directSplunkObservability",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directSplunkObservability:DirectSplunkObservability": "DirectSplunkObservability"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directSumologic",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directSumologic:DirectSumologic": "DirectSumologic"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/directThousandeyes",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/directThousandeyes:DirectThousandeyes": "DirectThousandeyes"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/project",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/project:Project": "Project"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/roleBinding",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/roleBinding:RoleBinding": "RoleBinding"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/service",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/service:Service": "Service"
  }
 },
 {
  "pkg": "nobl9",
  "mod": "index/slo",
  "fqn": "piclemx_pulumi_nobl9",
  "classes": {
   "nobl9:index/slo:Slo": "Slo"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "nobl9",
  "token": "pulumi:providers:nobl9",
  "fqn": "piclemx_pulumi_nobl9",
  "class": "Provider"
 }
]
"""
)
