// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Piclemx.Nobl9.Outputs
{

    [OutputType]
    public sealed class DirectAzureMonitorHistoricalDataRetrieval
    {
        /// <summary>
        /// Used by default for any SLOs connected to this data source.
        /// </summary>
        public readonly ImmutableArray<Outputs.DirectAzureMonitorHistoricalDataRetrievalDefaultDuration> DefaultDurations;
        /// <summary>
        /// Defines the maximum period for which data can be retrieved.
        /// </summary>
        public readonly ImmutableArray<Outputs.DirectAzureMonitorHistoricalDataRetrievalMaxDuration> MaxDurations;

        [OutputConstructor]
        private DirectAzureMonitorHistoricalDataRetrieval(
            ImmutableArray<Outputs.DirectAzureMonitorHistoricalDataRetrievalDefaultDuration> defaultDurations,

            ImmutableArray<Outputs.DirectAzureMonitorHistoricalDataRetrievalMaxDuration> maxDurations)
        {
            DefaultDurations = defaultDurations;
            MaxDurations = maxDurations;
        }
    }
}
