// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nobl9.Outputs
{

    [OutputType]
    public sealed class ServiceLabel
    {
        /// <summary>
        /// A key for the label, unique within the associated resource.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// A list of unique values for a single key.
        /// </summary>
        public readonly ImmutableArray<string> Values;

        [OutputConstructor]
        private ServiceLabel(
            string key,

            ImmutableArray<string> values)
        {
            Key = key;
            Values = values;
        }
    }
}
