// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nobl9.Outputs
{

    [OutputType]
    public sealed class SloObjectiveCountMetricTotalCloudwatchDimension
    {
        /// <summary>
        /// Unique name of the resource, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
        /// </summary>
        public readonly string Name;
        public readonly string Value;

        [OutputConstructor]
        private SloObjectiveCountMetricTotalCloudwatchDimension(
            string name,

            string value)
        {
            Name = name;
            Value = value;
        }
    }
}
