// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nobl9.Outputs
{

    [OutputType]
    public sealed class SloObjectiveRawMetric
    {
        public readonly ImmutableArray<Outputs.SloObjectiveRawMetricQuery> Queries;

        [OutputConstructor]
        private SloObjectiveRawMetric(ImmutableArray<Outputs.SloObjectiveRawMetricQuery> queries)
        {
            Queries = queries;
        }
    }
}
