// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nobl9

import (
	"context"
	"reflect"

	"errors"
	"github.com/piclemx/pulumi-nobl9/sdk/go/nobl9/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Instana is an observability platform that delivers automated Application Performance Monitoring (APM), used for website, infrastructure, and application monitoring. Nobl9 connects to Instana for SLI measurement collection and comparison with SLO targets.
//
// For more information, refer to [Instana Direct | Nobl9 Documentation](https://docs.nobl9.com/Sources/instana#instana-direct).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/piclemx/pulumi-nobl9/sdk/go/nobl9"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := nobl9.NewDirectInstana(ctx, "test-instana", &nobl9.DirectInstanaArgs{
//				ApiToken:             pulumi.String("secret"),
//				Description:          pulumi.String("desc"),
//				LogCollectionEnabled: pulumi.Bool(true),
//				Project:              pulumi.String("terraform"),
//				Url:                  pulumi.String("https://web.net"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// ## Nobl9 Official Documentation
//
// https://docs.nobl9.com/
type DirectInstana struct {
	pulumi.CustomResourceState

	// [required] | Instana API Token.
	ApiToken pulumi.StringOutput `pulumi:"apiToken"`
	// Optional description of the resource. Here, you can add details about who is responsible for the integration (team/owner) or the purpose of creating it.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// User-friendly display name of the resource.
	DisplayName pulumi.StringPtrOutput `pulumi:"displayName"`
	// [Logs documentation](https://docs.nobl9.com/Features/SLO_troubleshooting/event-logs)
	LogCollectionEnabled pulumi.BoolPtrOutput `pulumi:"logCollectionEnabled"`
	// Unique name of the resource, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
	Name pulumi.StringOutput `pulumi:"name"`
	// Name of the Nobl9 project the resource sits in, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
	Project pulumi.StringOutput `pulumi:"project"`
	// [Query delay configuration documentation](https://docs.nobl9.com/Features/query-delay). Computed if not provided.
	QueryDelay DirectInstanaQueryDelayOutput `pulumi:"queryDelay"`
	// Release channel of the created datasource [stable/beta]
	ReleaseChannel pulumi.StringOutput `pulumi:"releaseChannel"`
	// This value indicated whether the field was a source of metrics and/or services. 'source_of' is deprecated and not used anywhere; however, it's kept for backward compatibility.
	//
	// Deprecated: 'source_of' is deprecated and not used anywhere. You can safely remove it from your configuration file.
	SourceOfs pulumi.StringArrayOutput `pulumi:"sourceOfs"`
	// The status of the created direct.
	Status pulumi.StringOutput `pulumi:"status"`
	// Instana API URL.
	Url pulumi.StringOutput `pulumi:"url"`
}

// NewDirectInstana registers a new resource with the given unique name, arguments, and options.
func NewDirectInstana(ctx *pulumi.Context,
	name string, args *DirectInstanaArgs, opts ...pulumi.ResourceOption) (*DirectInstana, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Project == nil {
		return nil, errors.New("invalid value for required argument 'Project'")
	}
	if args.Url == nil {
		return nil, errors.New("invalid value for required argument 'Url'")
	}
	if args.ApiToken != nil {
		args.ApiToken = pulumi.ToSecret(args.ApiToken).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DirectInstana
	err := ctx.RegisterResource("nobl9:index/directInstana:DirectInstana", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDirectInstana gets an existing DirectInstana resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDirectInstana(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DirectInstanaState, opts ...pulumi.ResourceOption) (*DirectInstana, error) {
	var resource DirectInstana
	err := ctx.ReadResource("nobl9:index/directInstana:DirectInstana", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DirectInstana resources.
type directInstanaState struct {
	// [required] | Instana API Token.
	ApiToken *string `pulumi:"apiToken"`
	// Optional description of the resource. Here, you can add details about who is responsible for the integration (team/owner) or the purpose of creating it.
	Description *string `pulumi:"description"`
	// User-friendly display name of the resource.
	DisplayName *string `pulumi:"displayName"`
	// [Logs documentation](https://docs.nobl9.com/Features/SLO_troubleshooting/event-logs)
	LogCollectionEnabled *bool `pulumi:"logCollectionEnabled"`
	// Unique name of the resource, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
	Name *string `pulumi:"name"`
	// Name of the Nobl9 project the resource sits in, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
	Project *string `pulumi:"project"`
	// [Query delay configuration documentation](https://docs.nobl9.com/Features/query-delay). Computed if not provided.
	QueryDelay *DirectInstanaQueryDelay `pulumi:"queryDelay"`
	// Release channel of the created datasource [stable/beta]
	ReleaseChannel *string `pulumi:"releaseChannel"`
	// This value indicated whether the field was a source of metrics and/or services. 'source_of' is deprecated and not used anywhere; however, it's kept for backward compatibility.
	//
	// Deprecated: 'source_of' is deprecated and not used anywhere. You can safely remove it from your configuration file.
	SourceOfs []string `pulumi:"sourceOfs"`
	// The status of the created direct.
	Status *string `pulumi:"status"`
	// Instana API URL.
	Url *string `pulumi:"url"`
}

type DirectInstanaState struct {
	// [required] | Instana API Token.
	ApiToken pulumi.StringPtrInput
	// Optional description of the resource. Here, you can add details about who is responsible for the integration (team/owner) or the purpose of creating it.
	Description pulumi.StringPtrInput
	// User-friendly display name of the resource.
	DisplayName pulumi.StringPtrInput
	// [Logs documentation](https://docs.nobl9.com/Features/SLO_troubleshooting/event-logs)
	LogCollectionEnabled pulumi.BoolPtrInput
	// Unique name of the resource, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
	Name pulumi.StringPtrInput
	// Name of the Nobl9 project the resource sits in, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
	Project pulumi.StringPtrInput
	// [Query delay configuration documentation](https://docs.nobl9.com/Features/query-delay). Computed if not provided.
	QueryDelay DirectInstanaQueryDelayPtrInput
	// Release channel of the created datasource [stable/beta]
	ReleaseChannel pulumi.StringPtrInput
	// This value indicated whether the field was a source of metrics and/or services. 'source_of' is deprecated and not used anywhere; however, it's kept for backward compatibility.
	//
	// Deprecated: 'source_of' is deprecated and not used anywhere. You can safely remove it from your configuration file.
	SourceOfs pulumi.StringArrayInput
	// The status of the created direct.
	Status pulumi.StringPtrInput
	// Instana API URL.
	Url pulumi.StringPtrInput
}

func (DirectInstanaState) ElementType() reflect.Type {
	return reflect.TypeOf((*directInstanaState)(nil)).Elem()
}

type directInstanaArgs struct {
	// [required] | Instana API Token.
	ApiToken *string `pulumi:"apiToken"`
	// Optional description of the resource. Here, you can add details about who is responsible for the integration (team/owner) or the purpose of creating it.
	Description *string `pulumi:"description"`
	// User-friendly display name of the resource.
	DisplayName *string `pulumi:"displayName"`
	// [Logs documentation](https://docs.nobl9.com/Features/SLO_troubleshooting/event-logs)
	LogCollectionEnabled *bool `pulumi:"logCollectionEnabled"`
	// Unique name of the resource, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
	Name *string `pulumi:"name"`
	// Name of the Nobl9 project the resource sits in, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
	Project string `pulumi:"project"`
	// [Query delay configuration documentation](https://docs.nobl9.com/Features/query-delay). Computed if not provided.
	QueryDelay *DirectInstanaQueryDelay `pulumi:"queryDelay"`
	// Release channel of the created datasource [stable/beta]
	ReleaseChannel *string `pulumi:"releaseChannel"`
	// This value indicated whether the field was a source of metrics and/or services. 'source_of' is deprecated and not used anywhere; however, it's kept for backward compatibility.
	//
	// Deprecated: 'source_of' is deprecated and not used anywhere. You can safely remove it from your configuration file.
	SourceOfs []string `pulumi:"sourceOfs"`
	// Instana API URL.
	Url string `pulumi:"url"`
}

// The set of arguments for constructing a DirectInstana resource.
type DirectInstanaArgs struct {
	// [required] | Instana API Token.
	ApiToken pulumi.StringPtrInput
	// Optional description of the resource. Here, you can add details about who is responsible for the integration (team/owner) or the purpose of creating it.
	Description pulumi.StringPtrInput
	// User-friendly display name of the resource.
	DisplayName pulumi.StringPtrInput
	// [Logs documentation](https://docs.nobl9.com/Features/SLO_troubleshooting/event-logs)
	LogCollectionEnabled pulumi.BoolPtrInput
	// Unique name of the resource, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
	Name pulumi.StringPtrInput
	// Name of the Nobl9 project the resource sits in, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
	Project pulumi.StringInput
	// [Query delay configuration documentation](https://docs.nobl9.com/Features/query-delay). Computed if not provided.
	QueryDelay DirectInstanaQueryDelayPtrInput
	// Release channel of the created datasource [stable/beta]
	ReleaseChannel pulumi.StringPtrInput
	// This value indicated whether the field was a source of metrics and/or services. 'source_of' is deprecated and not used anywhere; however, it's kept for backward compatibility.
	//
	// Deprecated: 'source_of' is deprecated and not used anywhere. You can safely remove it from your configuration file.
	SourceOfs pulumi.StringArrayInput
	// Instana API URL.
	Url pulumi.StringInput
}

func (DirectInstanaArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*directInstanaArgs)(nil)).Elem()
}

type DirectInstanaInput interface {
	pulumi.Input

	ToDirectInstanaOutput() DirectInstanaOutput
	ToDirectInstanaOutputWithContext(ctx context.Context) DirectInstanaOutput
}

func (*DirectInstana) ElementType() reflect.Type {
	return reflect.TypeOf((**DirectInstana)(nil)).Elem()
}

func (i *DirectInstana) ToDirectInstanaOutput() DirectInstanaOutput {
	return i.ToDirectInstanaOutputWithContext(context.Background())
}

func (i *DirectInstana) ToDirectInstanaOutputWithContext(ctx context.Context) DirectInstanaOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DirectInstanaOutput)
}

// DirectInstanaArrayInput is an input type that accepts DirectInstanaArray and DirectInstanaArrayOutput values.
// You can construct a concrete instance of `DirectInstanaArrayInput` via:
//
//	DirectInstanaArray{ DirectInstanaArgs{...} }
type DirectInstanaArrayInput interface {
	pulumi.Input

	ToDirectInstanaArrayOutput() DirectInstanaArrayOutput
	ToDirectInstanaArrayOutputWithContext(context.Context) DirectInstanaArrayOutput
}

type DirectInstanaArray []DirectInstanaInput

func (DirectInstanaArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DirectInstana)(nil)).Elem()
}

func (i DirectInstanaArray) ToDirectInstanaArrayOutput() DirectInstanaArrayOutput {
	return i.ToDirectInstanaArrayOutputWithContext(context.Background())
}

func (i DirectInstanaArray) ToDirectInstanaArrayOutputWithContext(ctx context.Context) DirectInstanaArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DirectInstanaArrayOutput)
}

// DirectInstanaMapInput is an input type that accepts DirectInstanaMap and DirectInstanaMapOutput values.
// You can construct a concrete instance of `DirectInstanaMapInput` via:
//
//	DirectInstanaMap{ "key": DirectInstanaArgs{...} }
type DirectInstanaMapInput interface {
	pulumi.Input

	ToDirectInstanaMapOutput() DirectInstanaMapOutput
	ToDirectInstanaMapOutputWithContext(context.Context) DirectInstanaMapOutput
}

type DirectInstanaMap map[string]DirectInstanaInput

func (DirectInstanaMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DirectInstana)(nil)).Elem()
}

func (i DirectInstanaMap) ToDirectInstanaMapOutput() DirectInstanaMapOutput {
	return i.ToDirectInstanaMapOutputWithContext(context.Background())
}

func (i DirectInstanaMap) ToDirectInstanaMapOutputWithContext(ctx context.Context) DirectInstanaMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DirectInstanaMapOutput)
}

type DirectInstanaOutput struct{ *pulumi.OutputState }

func (DirectInstanaOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DirectInstana)(nil)).Elem()
}

func (o DirectInstanaOutput) ToDirectInstanaOutput() DirectInstanaOutput {
	return o
}

func (o DirectInstanaOutput) ToDirectInstanaOutputWithContext(ctx context.Context) DirectInstanaOutput {
	return o
}

// [required] | Instana API Token.
func (o DirectInstanaOutput) ApiToken() pulumi.StringOutput {
	return o.ApplyT(func(v *DirectInstana) pulumi.StringOutput { return v.ApiToken }).(pulumi.StringOutput)
}

// Optional description of the resource. Here, you can add details about who is responsible for the integration (team/owner) or the purpose of creating it.
func (o DirectInstanaOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DirectInstana) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// User-friendly display name of the resource.
func (o DirectInstanaOutput) DisplayName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DirectInstana) pulumi.StringPtrOutput { return v.DisplayName }).(pulumi.StringPtrOutput)
}

// [Logs documentation](https://docs.nobl9.com/Features/SLO_troubleshooting/event-logs)
func (o DirectInstanaOutput) LogCollectionEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DirectInstana) pulumi.BoolPtrOutput { return v.LogCollectionEnabled }).(pulumi.BoolPtrOutput)
}

// Unique name of the resource, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
func (o DirectInstanaOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *DirectInstana) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Name of the Nobl9 project the resource sits in, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
func (o DirectInstanaOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *DirectInstana) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

// [Query delay configuration documentation](https://docs.nobl9.com/Features/query-delay). Computed if not provided.
func (o DirectInstanaOutput) QueryDelay() DirectInstanaQueryDelayOutput {
	return o.ApplyT(func(v *DirectInstana) DirectInstanaQueryDelayOutput { return v.QueryDelay }).(DirectInstanaQueryDelayOutput)
}

// Release channel of the created datasource [stable/beta]
func (o DirectInstanaOutput) ReleaseChannel() pulumi.StringOutput {
	return o.ApplyT(func(v *DirectInstana) pulumi.StringOutput { return v.ReleaseChannel }).(pulumi.StringOutput)
}

// This value indicated whether the field was a source of metrics and/or services. 'source_of' is deprecated and not used anywhere; however, it's kept for backward compatibility.
//
// Deprecated: 'source_of' is deprecated and not used anywhere. You can safely remove it from your configuration file.
func (o DirectInstanaOutput) SourceOfs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DirectInstana) pulumi.StringArrayOutput { return v.SourceOfs }).(pulumi.StringArrayOutput)
}

// The status of the created direct.
func (o DirectInstanaOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *DirectInstana) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Instana API URL.
func (o DirectInstanaOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *DirectInstana) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

type DirectInstanaArrayOutput struct{ *pulumi.OutputState }

func (DirectInstanaArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DirectInstana)(nil)).Elem()
}

func (o DirectInstanaArrayOutput) ToDirectInstanaArrayOutput() DirectInstanaArrayOutput {
	return o
}

func (o DirectInstanaArrayOutput) ToDirectInstanaArrayOutputWithContext(ctx context.Context) DirectInstanaArrayOutput {
	return o
}

func (o DirectInstanaArrayOutput) Index(i pulumi.IntInput) DirectInstanaOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DirectInstana {
		return vs[0].([]*DirectInstana)[vs[1].(int)]
	}).(DirectInstanaOutput)
}

type DirectInstanaMapOutput struct{ *pulumi.OutputState }

func (DirectInstanaMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DirectInstana)(nil)).Elem()
}

func (o DirectInstanaMapOutput) ToDirectInstanaMapOutput() DirectInstanaMapOutput {
	return o
}

func (o DirectInstanaMapOutput) ToDirectInstanaMapOutputWithContext(ctx context.Context) DirectInstanaMapOutput {
	return o
}

func (o DirectInstanaMapOutput) MapIndex(k pulumi.StringInput) DirectInstanaOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DirectInstana {
		return vs[0].(map[string]*DirectInstana)[vs[1].(string)]
	}).(DirectInstanaOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DirectInstanaInput)(nil)).Elem(), &DirectInstana{})
	pulumi.RegisterInputType(reflect.TypeOf((*DirectInstanaArrayInput)(nil)).Elem(), DirectInstanaArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DirectInstanaMapInput)(nil)).Elem(), DirectInstanaMap{})
	pulumi.RegisterOutputType(DirectInstanaOutput{})
	pulumi.RegisterOutputType(DirectInstanaArrayOutput{})
	pulumi.RegisterOutputType(DirectInstanaMapOutput{})
}
