// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Piclemx.Nobl9.Inputs
{

    public sealed class SloObjectiveCountMetricBadSumologicGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Period of data aggregation
        /// </summary>
        [Input("quantization")]
        public Input<string>? Quantization { get; set; }

        /// <summary>
        /// Query for the metrics
        /// </summary>
        [Input("query", required: true)]
        public Input<string> Query { get; set; } = null!;

        /// <summary>
        /// Aggregation function - avg, sum, min, max, count, none
        /// </summary>
        [Input("rollup")]
        public Input<string>? Rollup { get; set; }

        /// <summary>
        /// Sumologic source - metrics or logs
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public SloObjectiveCountMetricBadSumologicGetArgs()
        {
        }
        public static new SloObjectiveCountMetricBadSumologicGetArgs Empty => new SloObjectiveCountMetricBadSumologicGetArgs();
    }
}
