// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nobl9.Inputs
{

    public sealed class SloObjectiveRawMetricQueryCloudwatchDimensionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Unique name of the resource, must conform to the naming convention from [DNS RFC1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public SloObjectiveRawMetricQueryCloudwatchDimensionGetArgs()
        {
        }
        public static new SloObjectiveRawMetricQueryCloudwatchDimensionGetArgs Empty => new SloObjectiveRawMetricQueryCloudwatchDimensionGetArgs();
    }
}
