// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nobl9.Inputs
{

    public sealed class SloObjectiveRawMetricArgs : global::Pulumi.ResourceArgs
    {
        [Input("queries")]
        private InputList<Inputs.SloObjectiveRawMetricQueryArgs>? _queries;
        public InputList<Inputs.SloObjectiveRawMetricQueryArgs> Queries
        {
            get => _queries ?? (_queries = new InputList<Inputs.SloObjectiveRawMetricQueryArgs>());
            set => _queries = value;
        }

        public SloObjectiveRawMetricArgs()
        {
        }
        public static new SloObjectiveRawMetricArgs Empty => new SloObjectiveRawMetricArgs();
    }
}
