// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Piclemx.Nobl9.Inputs
{

    public sealed class SloObjectiveCountMetricGoodArgs : global::Pulumi.ResourceArgs
    {
        [Input("amazonPrometheuses")]
        private InputList<Inputs.SloObjectiveCountMetricGoodAmazonPrometheusArgs>? _amazonPrometheuses;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/Amazon_Prometheus/#creating-slos-with-ams-prometheus)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodAmazonPrometheusArgs> AmazonPrometheuses
        {
            get => _amazonPrometheuses ?? (_amazonPrometheuses = new InputList<Inputs.SloObjectiveCountMetricGoodAmazonPrometheusArgs>());
            set => _amazonPrometheuses = value;
        }

        [Input("appdynamics")]
        private InputList<Inputs.SloObjectiveCountMetricGoodAppdynamicArgs>? _appdynamics;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/appdynamics#creating-slos-with-appdynamics)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodAppdynamicArgs> Appdynamics
        {
            get => _appdynamics ?? (_appdynamics = new InputList<Inputs.SloObjectiveCountMetricGoodAppdynamicArgs>());
            set => _appdynamics = value;
        }

        [Input("azureMonitors")]
        private InputList<Inputs.SloObjectiveCountMetricGoodAzureMonitorArgs>? _azureMonitors;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/azure-monitor#creating-slos-with-azure-monitor)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodAzureMonitorArgs> AzureMonitors
        {
            get => _azureMonitors ?? (_azureMonitors = new InputList<Inputs.SloObjectiveCountMetricGoodAzureMonitorArgs>());
            set => _azureMonitors = value;
        }

        [Input("bigqueries")]
        private InputList<Inputs.SloObjectiveCountMetricGoodBigqueryArgs>? _bigqueries;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/bigquery#creating-slos-with-bigquery)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodBigqueryArgs> Bigqueries
        {
            get => _bigqueries ?? (_bigqueries = new InputList<Inputs.SloObjectiveCountMetricGoodBigqueryArgs>());
            set => _bigqueries = value;
        }

        [Input("cloudwatches")]
        private InputList<Inputs.SloObjectiveCountMetricGoodCloudwatchArgs>? _cloudwatches;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/Amazon_CloudWatch/#creating-slos-with-cloudwatch)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodCloudwatchArgs> Cloudwatches
        {
            get => _cloudwatches ?? (_cloudwatches = new InputList<Inputs.SloObjectiveCountMetricGoodCloudwatchArgs>());
            set => _cloudwatches = value;
        }

        [Input("datadogs")]
        private InputList<Inputs.SloObjectiveCountMetricGoodDatadogArgs>? _datadogs;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/datadog#creating-slos-with-datadog)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodDatadogArgs> Datadogs
        {
            get => _datadogs ?? (_datadogs = new InputList<Inputs.SloObjectiveCountMetricGoodDatadogArgs>());
            set => _datadogs = value;
        }

        [Input("dynatraces")]
        private InputList<Inputs.SloObjectiveCountMetricGoodDynatraceArgs>? _dynatraces;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/dynatrace#creating-slos-with-dynatrace)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodDynatraceArgs> Dynatraces
        {
            get => _dynatraces ?? (_dynatraces = new InputList<Inputs.SloObjectiveCountMetricGoodDynatraceArgs>());
            set => _dynatraces = value;
        }

        [Input("elasticsearches")]
        private InputList<Inputs.SloObjectiveCountMetricGoodElasticsearchArgs>? _elasticsearches;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/elasticsearch#creating-slos-with-elasticsearch)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodElasticsearchArgs> Elasticsearches
        {
            get => _elasticsearches ?? (_elasticsearches = new InputList<Inputs.SloObjectiveCountMetricGoodElasticsearchArgs>());
            set => _elasticsearches = value;
        }

        [Input("gcms")]
        private InputList<Inputs.SloObjectiveCountMetricGoodGcmArgs>? _gcms;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/google-cloud-monitoring#creating-slos-with-google-cloud-monitoring)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodGcmArgs> Gcms
        {
            get => _gcms ?? (_gcms = new InputList<Inputs.SloObjectiveCountMetricGoodGcmArgs>());
            set => _gcms = value;
        }

        [Input("grafanaLokis")]
        private InputList<Inputs.SloObjectiveCountMetricGoodGrafanaLokiArgs>? _grafanaLokis;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/grafana-loki#creating-slos-with-grafana-loki)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodGrafanaLokiArgs> GrafanaLokis
        {
            get => _grafanaLokis ?? (_grafanaLokis = new InputList<Inputs.SloObjectiveCountMetricGoodGrafanaLokiArgs>());
            set => _grafanaLokis = value;
        }

        [Input("graphites")]
        private InputList<Inputs.SloObjectiveCountMetricGoodGraphiteArgs>? _graphites;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/graphite#creating-slos-with-graphite)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodGraphiteArgs> Graphites
        {
            get => _graphites ?? (_graphites = new InputList<Inputs.SloObjectiveCountMetricGoodGraphiteArgs>());
            set => _graphites = value;
        }

        [Input("honeycombs")]
        private InputList<Inputs.SloObjectiveCountMetricGoodHoneycombArgs>? _honeycombs;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/honeycomb#creating-slos-with-honeycomb)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodHoneycombArgs> Honeycombs
        {
            get => _honeycombs ?? (_honeycombs = new InputList<Inputs.SloObjectiveCountMetricGoodHoneycombArgs>());
            set => _honeycombs = value;
        }

        [Input("influxdbs")]
        private InputList<Inputs.SloObjectiveCountMetricGoodInfluxdbArgs>? _influxdbs;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/influxdb#creating-slos-with-influxdb)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodInfluxdbArgs> Influxdbs
        {
            get => _influxdbs ?? (_influxdbs = new InputList<Inputs.SloObjectiveCountMetricGoodInfluxdbArgs>());
            set => _influxdbs = value;
        }

        [Input("instanas")]
        private InputList<Inputs.SloObjectiveCountMetricGoodInstanaArgs>? _instanas;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/instana#creating-slos-with-instana)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodInstanaArgs> Instanas
        {
            get => _instanas ?? (_instanas = new InputList<Inputs.SloObjectiveCountMetricGoodInstanaArgs>());
            set => _instanas = value;
        }

        [Input("lightsteps")]
        private InputList<Inputs.SloObjectiveCountMetricGoodLightstepArgs>? _lightsteps;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/lightstep#creating-slos-with-lightstep)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodLightstepArgs> Lightsteps
        {
            get => _lightsteps ?? (_lightsteps = new InputList<Inputs.SloObjectiveCountMetricGoodLightstepArgs>());
            set => _lightsteps = value;
        }

        [Input("newrelics")]
        private InputList<Inputs.SloObjectiveCountMetricGoodNewrelicArgs>? _newrelics;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/new-relic#creating-slos-with-new-relic)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodNewrelicArgs> Newrelics
        {
            get => _newrelics ?? (_newrelics = new InputList<Inputs.SloObjectiveCountMetricGoodNewrelicArgs>());
            set => _newrelics = value;
        }

        [Input("opentsdbs")]
        private InputList<Inputs.SloObjectiveCountMetricGoodOpentsdbArgs>? _opentsdbs;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/opentsdb#creating-slos-with-opentsdb)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodOpentsdbArgs> Opentsdbs
        {
            get => _opentsdbs ?? (_opentsdbs = new InputList<Inputs.SloObjectiveCountMetricGoodOpentsdbArgs>());
            set => _opentsdbs = value;
        }

        [Input("pingdoms")]
        private InputList<Inputs.SloObjectiveCountMetricGoodPingdomArgs>? _pingdoms;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/pingdom#creating-slos-with-pingdom)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodPingdomArgs> Pingdoms
        {
            get => _pingdoms ?? (_pingdoms = new InputList<Inputs.SloObjectiveCountMetricGoodPingdomArgs>());
            set => _pingdoms = value;
        }

        [Input("prometheuses")]
        private InputList<Inputs.SloObjectiveCountMetricGoodPrometheusArgs>? _prometheuses;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/prometheus#creating-slos-with-prometheus)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodPrometheusArgs> Prometheuses
        {
            get => _prometheuses ?? (_prometheuses = new InputList<Inputs.SloObjectiveCountMetricGoodPrometheusArgs>());
            set => _prometheuses = value;
        }

        [Input("redshifts")]
        private InputList<Inputs.SloObjectiveCountMetricGoodRedshiftArgs>? _redshifts;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/Amazon_Redshift/#creating-slos-with-amazon-redshift)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodRedshiftArgs> Redshifts
        {
            get => _redshifts ?? (_redshifts = new InputList<Inputs.SloObjectiveCountMetricGoodRedshiftArgs>());
            set => _redshifts = value;
        }

        [Input("splunkObservabilities")]
        private InputList<Inputs.SloObjectiveCountMetricGoodSplunkObservabilityArgs>? _splunkObservabilities;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/splunk#creating-slos-with-splunk-observability)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodSplunkObservabilityArgs> SplunkObservabilities
        {
            get => _splunkObservabilities ?? (_splunkObservabilities = new InputList<Inputs.SloObjectiveCountMetricGoodSplunkObservabilityArgs>());
            set => _splunkObservabilities = value;
        }

        [Input("splunks")]
        private InputList<Inputs.SloObjectiveCountMetricGoodSplunkArgs>? _splunks;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/splunk#creating-slos-with-splunk)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodSplunkArgs> Splunks
        {
            get => _splunks ?? (_splunks = new InputList<Inputs.SloObjectiveCountMetricGoodSplunkArgs>());
            set => _splunks = value;
        }

        [Input("sumologics")]
        private InputList<Inputs.SloObjectiveCountMetricGoodSumologicArgs>? _sumologics;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/sumo-logic#creating-slos-with-sumo-logic)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodSumologicArgs> Sumologics
        {
            get => _sumologics ?? (_sumologics = new InputList<Inputs.SloObjectiveCountMetricGoodSumologicArgs>());
            set => _sumologics = value;
        }

        [Input("thousandeyes")]
        private InputList<Inputs.SloObjectiveCountMetricGoodThousandeyeArgs>? _thousandeyes;

        /// <summary>
        /// [Configuration documentation](https://docs.nobl9.com/Sources/thousandeyes#creating-slos-with-thousandeyes)
        /// </summary>
        public InputList<Inputs.SloObjectiveCountMetricGoodThousandeyeArgs> Thousandeyes
        {
            get => _thousandeyes ?? (_thousandeyes = new InputList<Inputs.SloObjectiveCountMetricGoodThousandeyeArgs>());
            set => _thousandeyes = value;
        }

        public SloObjectiveCountMetricGoodArgs()
        {
        }
        public static new SloObjectiveCountMetricGoodArgs Empty => new SloObjectiveCountMetricGoodArgs();
    }
}
