// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Piclemx.Nobl9.Inputs
{

    public sealed class SloObjectiveRawMetricGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("queries", required: true)]
        private InputList<Inputs.SloObjectiveRawMetricQueryGetArgs>? _queries;

        /// <summary>
        /// Query for the metrics
        /// </summary>
        public InputList<Inputs.SloObjectiveRawMetricQueryGetArgs> Queries
        {
            get => _queries ?? (_queries = new InputList<Inputs.SloObjectiveRawMetricQueryGetArgs>());
            set => _queries = value;
        }

        public SloObjectiveRawMetricGetArgs()
        {
        }
        public static new SloObjectiveRawMetricGetArgs Empty => new SloObjectiveRawMetricGetArgs();
    }
}
