// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nobl9.Inputs
{

    public sealed class SloObjectiveCountMetricGoodThousandeyeGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("testId", required: true)]
        public Input<int> TestId { get; set; } = null!;

        public SloObjectiveCountMetricGoodThousandeyeGetArgs()
        {
        }
        public static new SloObjectiveCountMetricGoodThousandeyeGetArgs Empty => new SloObjectiveCountMetricGoodThousandeyeGetArgs();
    }
}
