// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Returns external ID and AWS account ID that can be used to create [cross-account IAM roles in AWS](https://docs.nobl9.com/Sources/Amazon_CloudWatch/#cross-account-iam-roles-new).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as nobl9 from "@pulumi/nobl9";
 *
 * const this = nobl9.getAwsIamRoleExternalId({
 *     name: "my-datasource-name",
 * });
 * ```
 */
export function getAwsIamRoleExternalId(args: GetAwsIamRoleExternalIdArgs, opts?: pulumi.InvokeOptions): Promise<GetAwsIamRoleExternalIdResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nobl9:index/getAwsIamRoleExternalId:getAwsIamRoleExternalId", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getAwsIamRoleExternalId.
 */
export interface GetAwsIamRoleExternalIdArgs {
    /**
     * Data source name
     */
    name: string;
}

/**
 * A collection of values returned by getAwsIamRoleExternalId.
 */
export interface GetAwsIamRoleExternalIdResult {
    /**
     * External ID
     */
    readonly accountId: string;
    /**
     * Nobl9 AWS Account ID
     */
    readonly externalId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Data source name
     */
    readonly name: string;
}
/**
 * Returns external ID and AWS account ID that can be used to create [cross-account IAM roles in AWS](https://docs.nobl9.com/Sources/Amazon_CloudWatch/#cross-account-iam-roles-new).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as nobl9 from "@pulumi/nobl9";
 *
 * const this = nobl9.getAwsIamRoleExternalId({
 *     name: "my-datasource-name",
 * });
 * ```
 */
export function getAwsIamRoleExternalIdOutput(args: GetAwsIamRoleExternalIdOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAwsIamRoleExternalIdResult> {
    return pulumi.output(args).apply((a: any) => getAwsIamRoleExternalId(a, opts))
}

/**
 * A collection of arguments for invoking getAwsIamRoleExternalId.
 */
export interface GetAwsIamRoleExternalIdOutputArgs {
    /**
     * Data source name
     */
    name: pulumi.Input<string>;
}
